a=int(input("enter a value"))
b=int(input("enter b value"))
print("ARITHMETIC")
print(a+b)
print("sub",a-b)
print("mul",a*b)
print("div",a/b)
print("mod",a%b)
print("ASSIGNMENT")
a+=10
print(a)
a-=3
print("relational")
print(a>b)
print(a<b)
print(a<=b)
print(a>=b)
print(a==b)
print("logical")
print(a and b)
print(a or b)
print(a & b)
print("bitwise")
print(a | b)
print(a << b)
print(a >> b)
print("floor",a//b)
print(a >> b)
print(a >> b)
print("identity")
print(a is b)
print(a is not b)